// Generated by gencpp from file nao_dcm_msgs/BoolServiceResponse.msg
// DO NOT EDIT!


#ifndef NAO_DCM_MSGS_MESSAGE_BOOLSERVICERESPONSE_H
#define NAO_DCM_MSGS_MESSAGE_BOOLSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_dcm_msgs
{
template <class ContainerAllocator>
struct BoolServiceResponse_
{
  typedef BoolServiceResponse_<ContainerAllocator> Type;

  BoolServiceResponse_()
    {
    }
  BoolServiceResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BoolServiceResponse_

typedef ::nao_dcm_msgs::BoolServiceResponse_<std::allocator<void> > BoolServiceResponse;

typedef boost::shared_ptr< ::nao_dcm_msgs::BoolServiceResponse > BoolServiceResponsePtr;
typedef boost::shared_ptr< ::nao_dcm_msgs::BoolServiceResponse const> BoolServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_dcm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nao_dcm_msgs': ['/home/charles/catkin_ws/src/nao_dcm/nao_dcm_robot/nao_dcm_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_dcm_msgs/BoolServiceResponse";
  }

  static const char* value(const ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BoolServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::nao_dcm_msgs::BoolServiceResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAO_DCM_MSGS_MESSAGE_BOOLSERVICERESPONSE_H
