// Generated by gencpp from file nao_dcm_msgs/Bumper.msg
// DO NOT EDIT!


#ifndef NAO_DCM_MSGS_MESSAGE_BUMPER_H
#define NAO_DCM_MSGS_MESSAGE_BUMPER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_dcm_msgs
{
template <class ContainerAllocator>
struct Bumper_
{
  typedef Bumper_<ContainerAllocator> Type;

  Bumper_()
    : LeftFootLeft(0)
    , LeftFootRight(0)
    , RightFootLeft(0)
    , RightFootRight(0)  {
    }
  Bumper_(const ContainerAllocator& _alloc)
    : LeftFootLeft(0)
    , LeftFootRight(0)
    , RightFootLeft(0)
    , RightFootRight(0)  {
  (void)_alloc;
    }



   typedef uint8_t _LeftFootLeft_type;
  _LeftFootLeft_type LeftFootLeft;

   typedef uint8_t _LeftFootRight_type;
  _LeftFootRight_type LeftFootRight;

   typedef uint8_t _RightFootLeft_type;
  _RightFootLeft_type RightFootLeft;

   typedef uint8_t _RightFootRight_type;
  _RightFootRight_type RightFootRight;


    enum { stateUnPressed = 0u };
     enum { statePressed = 1u };
 

  typedef boost::shared_ptr< ::nao_dcm_msgs::Bumper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_dcm_msgs::Bumper_<ContainerAllocator> const> ConstPtr;

}; // struct Bumper_

typedef ::nao_dcm_msgs::Bumper_<std::allocator<void> > Bumper;

typedef boost::shared_ptr< ::nao_dcm_msgs::Bumper > BumperPtr;
typedef boost::shared_ptr< ::nao_dcm_msgs::Bumper const> BumperConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_dcm_msgs::Bumper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_dcm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nao_dcm_msgs': ['/home/charles/catkin_ws/src/nao_dcm/nao_dcm_robot/nao_dcm_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_dcm_msgs::Bumper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_dcm_msgs::Bumper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_dcm_msgs::Bumper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f3cee4c6e38d05c85e9a5767766a117";
  }

  static const char* value(const ::nao_dcm_msgs::Bumper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f3cee4c6e38d05cULL;
  static const uint64_t static_value2 = 0x85e9a5767766a117ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_dcm_msgs/Bumper";
  }

  static const char* value(const ::nao_dcm_msgs::Bumper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 stateUnPressed=0\n\
uint8 statePressed=1\n\
\n\
uint8 LeftFootLeft\n\
uint8 LeftFootRight\n\
\n\
uint8 RightFootLeft\n\
uint8 RightFootRight\n\
";
  }

  static const char* value(const ::nao_dcm_msgs::Bumper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LeftFootLeft);
      stream.next(m.LeftFootRight);
      stream.next(m.RightFootLeft);
      stream.next(m.RightFootRight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Bumper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_dcm_msgs::Bumper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_dcm_msgs::Bumper_<ContainerAllocator>& v)
  {
    s << indent << "LeftFootLeft: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LeftFootLeft);
    s << indent << "LeftFootRight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LeftFootRight);
    s << indent << "RightFootLeft: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RightFootLeft);
    s << indent << "RightFootRight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RightFootRight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_DCM_MSGS_MESSAGE_BUMPER_H
