// Generated by gencpp from file nao_dcm_msgs/Tactile.msg
// DO NOT EDIT!


#ifndef NAO_DCM_MSGS_MESSAGE_TACTILE_H
#define NAO_DCM_MSGS_MESSAGE_TACTILE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_dcm_msgs
{
template <class ContainerAllocator>
struct Tactile_
{
  typedef Tactile_<ContainerAllocator> Type;

  Tactile_()
    : HeadTouchRear(0)
    , HeadTouchMiddle(0)
    , HeadTouchFront(0)
    , LeftTouchBack(0)
    , LeftTouchLeft(0)
    , LeftTouchRight(0)
    , RightTouchBack(0)
    , RightTouchLeft(0)
    , RightTouchRight(0)  {
    }
  Tactile_(const ContainerAllocator& _alloc)
    : HeadTouchRear(0)
    , HeadTouchMiddle(0)
    , HeadTouchFront(0)
    , LeftTouchBack(0)
    , LeftTouchLeft(0)
    , LeftTouchRight(0)
    , RightTouchBack(0)
    , RightTouchLeft(0)
    , RightTouchRight(0)  {
  (void)_alloc;
    }



   typedef uint8_t _HeadTouchRear_type;
  _HeadTouchRear_type HeadTouchRear;

   typedef uint8_t _HeadTouchMiddle_type;
  _HeadTouchMiddle_type HeadTouchMiddle;

   typedef uint8_t _HeadTouchFront_type;
  _HeadTouchFront_type HeadTouchFront;

   typedef uint8_t _LeftTouchBack_type;
  _LeftTouchBack_type LeftTouchBack;

   typedef uint8_t _LeftTouchLeft_type;
  _LeftTouchLeft_type LeftTouchLeft;

   typedef uint8_t _LeftTouchRight_type;
  _LeftTouchRight_type LeftTouchRight;

   typedef uint8_t _RightTouchBack_type;
  _RightTouchBack_type RightTouchBack;

   typedef uint8_t _RightTouchLeft_type;
  _RightTouchLeft_type RightTouchLeft;

   typedef uint8_t _RightTouchRight_type;
  _RightTouchRight_type RightTouchRight;


    enum { stateUnPressed = 0u };
     enum { statePressed = 1u };
 

  typedef boost::shared_ptr< ::nao_dcm_msgs::Tactile_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_dcm_msgs::Tactile_<ContainerAllocator> const> ConstPtr;

}; // struct Tactile_

typedef ::nao_dcm_msgs::Tactile_<std::allocator<void> > Tactile;

typedef boost::shared_ptr< ::nao_dcm_msgs::Tactile > TactilePtr;
typedef boost::shared_ptr< ::nao_dcm_msgs::Tactile const> TactileConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_dcm_msgs::Tactile_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_dcm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nao_dcm_msgs': ['/home/charles/catkin_ws/src/nao_dcm/nao_dcm_robot/nao_dcm_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_dcm_msgs::Tactile_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_dcm_msgs::Tactile_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_dcm_msgs::Tactile_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8e6e983141612945d4fe93bd0192fe3";
  }

  static const char* value(const ::nao_dcm_msgs::Tactile_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8e6e98314161294ULL;
  static const uint64_t static_value2 = 0x5d4fe93bd0192fe3ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_dcm_msgs/Tactile";
  }

  static const char* value(const ::nao_dcm_msgs::Tactile_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 stateUnPressed=0\n\
uint8 statePressed=1\n\
\n\
uint8 HeadTouchRear\n\
uint8 HeadTouchMiddle\n\
uint8 HeadTouchFront\n\
\n\
uint8 LeftTouchBack\n\
uint8 LeftTouchLeft\n\
uint8 LeftTouchRight\n\
\n\
uint8 RightTouchBack\n\
uint8 RightTouchLeft\n\
uint8 RightTouchRight\n\
";
  }

  static const char* value(const ::nao_dcm_msgs::Tactile_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.HeadTouchRear);
      stream.next(m.HeadTouchMiddle);
      stream.next(m.HeadTouchFront);
      stream.next(m.LeftTouchBack);
      stream.next(m.LeftTouchLeft);
      stream.next(m.LeftTouchRight);
      stream.next(m.RightTouchBack);
      stream.next(m.RightTouchLeft);
      stream.next(m.RightTouchRight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Tactile_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_dcm_msgs::Tactile_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_dcm_msgs::Tactile_<ContainerAllocator>& v)
  {
    s << indent << "HeadTouchRear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HeadTouchRear);
    s << indent << "HeadTouchMiddle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HeadTouchMiddle);
    s << indent << "HeadTouchFront: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HeadTouchFront);
    s << indent << "LeftTouchBack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LeftTouchBack);
    s << indent << "LeftTouchLeft: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LeftTouchLeft);
    s << indent << "LeftTouchRight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LeftTouchRight);
    s << indent << "RightTouchBack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RightTouchBack);
    s << indent << "RightTouchLeft: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RightTouchLeft);
    s << indent << "RightTouchRight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RightTouchRight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_DCM_MSGS_MESSAGE_TACTILE_H
