(cl:in-package pal_detection_msgs-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          EYESLOCATED-VAL
          EYESLOCATED
          LEFTEYEX-VAL
          LEFTEYEX
          LEFTEYEY-VAL
          LEFTEYEY
          RIGHTEYEX-VAL
          RIGHTEYEX
          RIGHTEYEY-VAL
          RIGHTEYEY
          POSITION-VAL
          POSITION
          NAME-VAL
          NAME
          CONFIDENCE-VAL
          CONFIDENCE
          EXPRESSION-VAL
          EXPRESSION
          EXPRESSION_CONFIDENCE-VAL
          EXPRESSION_CONFIDENCE
))