# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nao_dcm_msgs/Bumper.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Bumper(genpy.Message):
  _md5sum = "8f3cee4c6e38d05c85e9a5767766a117"
  _type = "nao_dcm_msgs/Bumper"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 stateUnPressed=0
uint8 statePressed=1

uint8 LeftFootLeft
uint8 LeftFootRight

uint8 RightFootLeft
uint8 RightFootRight"""
  # Pseudo-constants
  stateUnPressed = 0
  statePressed = 1

  __slots__ = ['LeftFootLeft','LeftFootRight','RightFootLeft','RightFootRight']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       LeftFootLeft,LeftFootRight,RightFootLeft,RightFootRight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Bumper, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.LeftFootLeft is None:
        self.LeftFootLeft = 0
      if self.LeftFootRight is None:
        self.LeftFootRight = 0
      if self.RightFootLeft is None:
        self.RightFootLeft = 0
      if self.RightFootRight is None:
        self.RightFootRight = 0
    else:
      self.LeftFootLeft = 0
      self.LeftFootRight = 0
      self.RightFootLeft = 0
      self.RightFootRight = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.LeftFootLeft, _x.LeftFootRight, _x.RightFootLeft, _x.RightFootRight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.LeftFootLeft, _x.LeftFootRight, _x.RightFootLeft, _x.RightFootRight,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.LeftFootLeft, _x.LeftFootRight, _x.RightFootLeft, _x.RightFootRight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.LeftFootLeft, _x.LeftFootRight, _x.RightFootLeft, _x.RightFootRight,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
