(cl:in-package nao_dcm_msgs-msg)
(cl:export '(HEADTOUCHREAR-VAL
          HEADTOUCHREAR
          HEADTOUCHMIDDLE-VAL
          HEADTOUCHMIDDLE
          HEADTOUCHFRONT-VAL
          HEADTOUCHFRONT
          LEFTTOUCHBACK-VAL
          LEFTTOUCHBACK
          LEFTTOUCHLEFT-VAL
          LEFTTOUCHLEFT
          LEFTTOUCHRIGHT-VAL
          LEFTTOUCHRIGHT
          RIGHTTOUCHBACK-VAL
          RIGHTTOUCHBACK
          RIGHTTOUCHLEFT-VAL
          RIGHTTOUCHLEFT
          RIGHTTOUCHRIGHT-VAL
          RIGHTTOUCHRIGHT
))